version: ~> 1.0
dist: xenial
os: linux
language: java

cache:
  directories:
    - ~/.m2

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet
      - ruby

branches:
  only:
    - master

install:
  - gem install chef-utils:16.6.14 mdl

jobs:
  fast_finish: true
  include:

    # this job do deploy maven repository
    # unit tests (openjdk8)
    - jdk: openjdk8
      env:
        - DESC="tests and deploy"
        - CMD="mvn -e --no-transfer-progress clean integration-test failsafe:verify
          -DargLine='-Xms1024m -Xmx2048m'"
        - DEPLOY="true"
        - USE_MAVEN_REPO="true"

    # No error testing - XWiki project non regression
    - jdk: openjdk8
      env:
        - DESC="non regression on XWiki project"
        - USE_MAVEN_REPO="true"
        - CMD="./.ci/validation.sh no-error-xwiki"

    # until https://github.com/checkstyle/checkstyle/issues/9984
    # Ensure that all modules are used in no exception configs
    # - env:
<<<<<<< HEAD
    #    - DESC="ensure that all modules are used in no exception configs"
    #    - CMD1="export PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    #    - CMD2="./.ci/travis/validation.sh verify-no-exception-configs"
    #    - CMD="$CMD1 && $CMD2"
=======
    #     - DESC="check permissions on all files"
    #     - CMD="./.ci/travis/travis.sh check-chmod"
    #     - SKIP_JOB_BY_FILES="false"

    # moved to azure-pipelines.yml
    # MacOS JDK8 verify (till cache is not working, we can not do verify)
    # - os: osx
    #   osx_image: xcode9.3
    #   env:
    #     - DESC="MacOS JDK8 verify, site, assembly"
    #     - CMD1="./.ci/travis/travis.sh osx-package"
    #     - CMD2="./.ci/travis/travis.sh osx-assembly"
    #     - CMD="$CMD1 && $CMD2"
    # MacOS JDK11 verify (till cache is not working, we can not do verify)
    # - os: osx
    #   osx_image: xcode10.1
    #   env:
    #     - DESC="MacOS JDK11 verify, site, assembly"
    #     - CMD1="./.ci/travis/travis.sh osx-package"
    #     - CMD2="./.ci/travis/travis.sh osx-assembly"
    #     - CMD="$CMD1 && $CMD2"
    # MacOS JDK13 verify (till cache is not working, we can not do verify)
    # - os: osx
    #   osx_image: xcode11.2
    #   env:
    #     - DESC="MacOS JDK13 verify, site, assembly"
    #     - CMD1="./.ci/travis/travis.sh osx-jdk13-package"
    #     - CMD2="./.ci/travis/travis.sh osx-jdk13-assembly"
    #     - CMD="$CMD1 && $CMD2"

    # moved to drone.yml
    # No error testing - simple-binary-encoding
    # - jdk: openjdk8
    #   env:
    #     - DESC="no error test on simple-binary-encoding"
    #     - USE_MAVEN_REPO="true"
    #     - CMD="./.ci/travis/travis.sh no-error-test-sbe"

    # No error testing - XWiki project non regression
    - jdk: openjdk8
      env:
        - DESC="non regression on XWiki project"
        - USE_MAVEN_REPO="true"
        - CMD="./.ci/travis/travis.sh no-error-xwiki"

    # moved to azure-pipelines.yml
    # versions to update
    # - jdk: openjdk8
    #   env:
    #     - DESC="print versions to update"
    #     - USE_MAVEN_REPO="true"
    #     - CMD="./.ci/travis/travis.sh versions"
    #     - SKIP_JOB_BY_FILES="false"
>>>>>>> db7215d... Issue #9242: Build also xwiki-rendering and xwiki-platform in the no regression travis job

    - jdk: openjdk8
      env:
        - DESC="no-exception-openjdk9-lucene-and-others-javadoc"
        - CMD1="mvn -e --no-transfer-progress clean install -Pno-validations"
        - CMD2="./.ci/no-exception-test.sh no-exception-lucene-and-others-javadoc"
        - CMD="$CMD1 && $CMD2"
        - USE_MAVEN_REPO="true"

    - jdk: openjdk8
      env:
        - DESC="no-exception-cassandra-storm-tapestry-javadoc"
        - CMD1="mvn -e --no-transfer-progress clean install -Pno-validations"
        - CMD2="./.ci/no-exception-test.sh no-exception-cassandra-storm-tapestry-javadoc"
        - CMD="$CMD1 && $CMD2"
        - USE_MAVEN_REPO="true"

    - jdk: openjdk8
      env:
        - DESC="no-exception-hadoop-apache-groovy-scouter-javadoc"
        - CMD1="mvn -e --no-transfer-progress clean install -Pno-validations"
        - CMD2="./.ci/no-exception-test.sh no-exception-hadoop-apache-groovy-scouter-javadoc"
        - CMD="$CMD1 && $CMD2"
        - USE_MAVEN_REPO="true"

    - jdk: openjdk8
      env:
        - DESC="no-exception-openjdk9-lucene-and-others"
        - CMD1="mvn -e --no-transfer-progress clean install -Pno-validations"
        - CMD2="./.ci/no-exception-test.sh no-exception-only-javadoc"
        - CMD="$CMD1 && $CMD2"
        - USE_MAVEN_REPO="true"

script:
  - SKIP_FILES1=".github|codeship-*|appveyor.yml|circleci"
  - SKIP_FILES2="|fast-forward-merge.sh|LICENSE|LICENSE.apache20|README.md|release.sh|RIGHTS.antlr"
  - SKIP_FILES3="|wercker.yml|wercker.sh|intellij-idea-inspections.xml"
  - SKIP_FILES4="|Jenkinsfile"
  - SKIP_FILES=$SKIP_FILES1$SKIP_FILES2$SKIP_FILES3$SKIP_FILES4
  - export RUN_JOB=1
  # - source ./.ci/common.sh
#  - |
#    if [ -z ${SKIP_JOB_BY_FILES+x} ]; then
#        SKIP_JOB_BY_FILES="recheck";
#    fi
  # should_run_job will change RUN_JOB variable
#  - should_run_job $SKIP_JOB_BY_FILES $SKIP_FILES
  - |
    set -e
    if [[ $RUN_JOB == 1 ]]; then
      MVN_SETTINGS=${TRAVIS_HOME}/.m2/settings.xml
      if [[ -f ${MVN_SETTINGS} ]]; then
        if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          sed -i'' -e "/<mirrors>/,/<\/mirrors>/ d" $MVN_SETTINGS
        else
          xmlstarlet ed --inplace -d "//mirrors" $MVN_SETTINGS
        fi
      fi
      if [[ $USE_MAVEN_REPO == 'true' && ! -d "~/.m2" ]]; then
       echo "Maven local repo cache is not found, initializing it ..."
       mvn -e --no-transfer-progress -B install -Pno-validations;
       mvn -e --no-transfer-progress clean;
      fi
      echo "eval of CMD is starting";
      echo "CMD=$CMD";
      eval $CMD;
      echo "eval of CMD is completed";
    else
      echo "CI is skipped";
    fi
    sleep 5s

after_success:
  - |
    set -e
    if [[ -n $CMD_AFTER_SUCCESS
          && $RUN_JOB == 1
       ]];
    then
        echo "CMD_AFTER_SUCCESS is starting";
        eval $CMD_AFTER_SUCCESS;
        echo "CMD_AFTER_SUCCESS is finished";
    fi
    sleep 5s

  - |
    set -e
    SKIP_DEPLOY=false
    if [ $(git log -1 | grep -E "\[maven-release-plugin\] prepare release" | cat | wc -l) -lt 1 ];
      then
        SKIP_DEPLOY=false;
      else
        SKIP_DEPLOY=true;
    fi;
    if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
            && $TRAVIS_BRANCH == 'master'
            && $TRAVIS_PULL_REQUEST == 'false'
            && $DEPLOY == 'true'
            && $RUN_JOB == 1
            && $SKIP_DEPLOY == 'false'
       ]];
    then
        mvn -e --no-transfer-progress -s config/deploy-settings.xml -Pno-validations deploy;
        echo "deploy to maven snapshot repository is finished";
    fi
    sleep 5s
  - |
    set -e
      if [ "$(git status | grep 'Changes not staged\|Untracked files')" ]; then
        printf "Please clean up or update .gitattributes file.\nGit status output:\n"
        git status
        printf "Top 300 lines of diff:\n"
        git diff | head -n 300
        sleep 5s
        false
      fi
  - |
    set -e
    fail=0
    mkdir -p .ci-temp
    if [ -z "$(ls -A .ci-temp)" ]; then
        echo "Folder .ci-temp/ is empty."
    else
        echo "Folder .ci-temp/ is not empty. Verification failed."
        echo "Contents of .ci-temp/:"
        fail=1
    fi
    ls -A .ci-temp
    sleep 5s
    exit $fail
